server:
  port: 8102
spring:
  application:
    name: spca-gateway
  # 注册中心配置
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.200:8848
        namespace: d7524619-c92f-4bd4-95e7-b0640804334e
        cluster-name: NanJing
        metadata:
          service-version: 2020.1004
          api-info: The lastest Api.
    gateway:
#      discovery:
#        locator:
#          enabled: true
      routes:
#        - id: some_route
#          uri: http://www.baidu.com
#          predicates:
#            - Path=/user/2
#          filters:
#            - AddRequestHeader=X-Request-Foo,Bar
        # 用户中心微服务
        - id: user-route
          uri: lb://spca-user
          predicates:
            - Path=/user-center/**
          filters:
            - StripPrefix=1
        # 内容中心微服务
        - id: content-route
          uri: lb://spca-content
          predicates:
            - Path=/content-center/**
            #- TimeBetween=2020-11-01,2020-11-30
          filters:
            - StripPrefix=1
            - PreLog=key1,value1
  zipkin:
    base-url: http://192.168.1.124:9411/
    # 禁止Zipkin作为服务发现客户端，注意原配置不起效 discovery-client-enabled: false
    discoveryClientEnabled: false
  sleuth:
    sampler:
      # 抽样率，默认0.1（10%）
      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
# 打印日志
logging:
  level:
    com.wzliulan.demo.spca: debug
    com.alibaba.nacos: error

